sonar.projectKey=jenkins-pipeline-node-app
sonar.projectName=Jenkins Pipeline Node App
sonar.projectVersion=1.0

# Source Settings
sonar.sources=.

# Encoding Settings
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**

# Token Authentication (Replace with your real token)
sonar.token=sqa_74dd1304324d7d08a7c87c1c4b6b7e6c37e7e8b7

