sonar.projectKey=jenkins-pipeline-node-app
sonar.projectName=Jenkins Pipeline Node App
sonar.projectVersion=1.0

# Source Settings
sonar.sources=.

# Language Settings
sonar.language=js

# Encoding Settings
sonar.sourceEncoding=UTF-8

# Exclusions (optional, customize as needed)
sonar.exclusions=**/node_modules/**

# Token Authentication (Replace with real token from SonarQube UI)
sonar.token=sqa_72573beb918c7908559bc1a5a9a71f6e517ac5da

